const express = require("express");
const homeController = require("../controllers/home.controller");
const userController = require("../controllers/user.controller");
// const authMiddleware = require("../middlewares/auth.middleware");
// const permissionMiddleware = require("../middlewares/permission.middleware");
const router = express.Router();
router.get("/", homeController.index.bind(homeController));
// router.use(authMiddleware, permissionMiddleware);
router.get("/users", userController.index);
router.get("/users/:id", userController.find);
router.post("/users", userController.create);
router.put("/users/:id", userController.update);
router.delete("/users/:id", userController.destroy);
router.post("/users/:id/restore", userController.restore);
module.exports = router;
